# MaxMind GeoIP Update Configuration
# Used by the geoipupdate Docker container.
# License key is injected via environment variables in docker-compose.yml.
#
# To obtain a free license key:
# 1. Register at https://www.maxmind.com/en/geolite2/signup
# 2. Generate a license key in your account
# 3. Set MAXMIND_ACCOUNT_ID and MAXMIND_LICENSE_KEY in deploy/.env

AccountID YOUR_ACCOUNT_ID
LicenseKey YOUR_LICENSE_KEY
EditionIDs GeoLite2-City
DatabaseDirectory /usr/share/GeoIP
